In [5]:
import os 
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns 
from pathlib import Path


%store -r df_eda_v1

In [10]:
df_eda_v1

shape: (21_529, 32)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ market_id  ┆ market_slu ┆ crypto ┆ timeframe ┆ … ┆ trailing_ ┆ taker_bas ┆ maker_bas ┆ market_da │
│ ---        ┆ g          ┆ ---    ┆ ---       ┆   ┆ 60s_imbal ┆ e_fee     ┆ e_fee     ┆ te        │
│ str        ┆ ---        ┆ str    ┆ str       ┆   ┆ ance      ┆ ---       ┆ ---       ┆ ---       │
│            ┆ str        ┆        ┆           ┆   ┆ ---       ┆ f64       ┆ f64       ┆ date      │
│            ┆            ┆        ┆           ┆   ┆ f64       ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0xee052e97 ┆ btc-updown ┆ BTC    ┆ 5-minute  ┆ … ┆ -0.818133 ┆ 1000.0    ┆ 1000.0    ┆ 2026-02-1 │
│ 49e36868aa ┆ -5m-177085 ┆        ┆           ┆   ┆           ┆           ┆           ┆ 2         │
│ eea7efb875 ┆ 8600       ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0xd4bb645f ┆ btc-updown ┆ BTC    ┆ 5-minute  ┆ … ┆ 0.77697   ┆ 1000.0    ┆ 1000.0    ┆ 2026-02-1 │
│ 374beb0781 ┆ -5m-177085 ┆        ┆           ┆   ┆           ┆           ┆           ┆ 2         │
│ 57da12cd4f ┆ 8900       ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0x72b05d06 ┆ btc-updown ┆ BTC    ┆ 5-minute  ┆ … ┆ -0.478259 ┆ 1000.0    ┆ 1000.0    ┆ 2026-02-1 │
│ e0a8ccc2a9 ┆ -5m-177085 ┆        ┆           ┆   ┆           ┆           ┆           ┆ 2         │
│ 86bcda9a71 ┆ 9200       ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0x808c50a4 ┆ btc-updown ┆ BTC    ┆ 5-minute  ┆ … ┆ -0.879849 ┆ 1000.0    ┆ 1000.0    ┆ 2026-02-1 │
│ 48b4381069 ┆ -5m-177085 ┆        ┆           ┆   ┆           ┆           ┆           ┆ 2         │
│ 58d188f8b3 ┆ 9500       ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0xe7710c18 ┆ btc-updown ┆ BTC    ┆ 5-minute  ┆ … ┆ -0.206099 ┆ 1000.0    ┆ 1000.0    ┆ 2026-02-1 │
│ 2b8b36312f ┆ -5m-177085 ┆        ┆           ┆   ┆           ┆           ┆           ┆ 2         │
│ b7d90bc2fc ┆ 9800       ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …      ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 0x255da457 ┆ btc-updown ┆ BTC    ┆ 5-minute  ┆ … ┆ 0.217038  ┆ 1000.0    ┆ 1000.0    ┆ 2026-04-2 │
│ b9c2cbd8e8 ┆ -5m-177733 ┆        ┆           ┆   ┆           ┆           ┆           ┆ 7         │
│ a09c2dec6a ┆ 2900       ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0x155add1d ┆ btc-updown ┆ BTC    ┆ 5-minute  ┆ … ┆ -0.871885 ┆ 1000.0    ┆ 1000.0    ┆ 2026-04-2 │
│ 1a7eda2e33 ┆ -5m-177733 ┆        ┆           ┆   ┆           ┆           ┆           ┆ 7         │
│ 940a3fbdec ┆ 3200       ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0xd2b24374 ┆ btc-updown ┆ BTC    ┆ 5-minute  ┆ … ┆ -0.137375 ┆ 1000.0    ┆ 1000.0    ┆ 2026-04-2 │
│ e1376b6b47 ┆ -5m-177733 ┆        ┆           ┆   ┆           ┆           ┆           ┆ 7         │
│ 6d56b6a895 ┆ 3500       ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0xe261032a ┆ btc-updown ┆ BTC    ┆ 5-minute  ┆ … ┆ 0.080996  ┆ 1000.0    ┆ 1000.0    ┆ 2026-04-2 │
│ 80bcf728ae ┆ -5m-177733 ┆        ┆           ┆   ┆           ┆           ┆           ┆ 7         │
│ 3fc69de818 ┆ 3800       ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0x20894e81 ┆ btc-updown ┆ BTC    ┆ 5-minute  ┆ … ┆ 0.784826  ┆ 1000.0    ┆ 1000.0    ┆ 2026-04-2 │
│ 97b4c8cae2 ┆ -5m-177733 ┆        ┆           ┆   ┆           ┆           ┆           ┆ 7         │
│ 42bf94e6fb ┆ 4100       ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [18]:
# construct feature matrix, X, y 

df_feature_matrix = df_eda_v1.drop(
    "market_slug",
    "crypto",
    "timeframe",
    "opens_at",
    "close_at",
    "market_date",
    "winning_outcome_label",
    "resolution_status",
    "resolved_at"
)

feature_cols = [
    ""


]


metadata = df_eda_v1.select(["market_id","prediction_ts"])
y = df_feature_matrix.get_column("resolution")

df_feature_matrix.head()

shape: (5, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ market_id ┆ resolutio ┆ start_ts  ┆ end_ts    ┆ … ┆ trailing_ ┆ trailing_ ┆ taker_bas ┆ maker_ba │
│ ---       ┆ n         ┆ ---       ┆ ---       ┆   ┆ 60s_signe ┆ 60s_imbal ┆ e_fee     ┆ se_fee   │
│ str       ┆ ---       ┆ i64       ┆ i64       ┆   ┆ d_flow_us ┆ ance      ┆ ---       ┆ ---      │
│           ┆ i8        ┆           ┆           ┆   ┆ dc        ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0xee052e9 ┆ 1         ┆ 177085689 ┆ 177085890 ┆ … ┆ -2.699111 ┆ -0.818133 ┆ 1000.0    ┆ 1000.0   │
│ 749e36868 ┆           ┆ 7         ┆ 0         ┆   ┆           ┆           ┆           ┆          │
│ aaeea7efb ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 875…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0xd4bb645 ┆ 0         ┆ 177085716 ┆ 177085920 ┆ … ┆ 6.967396  ┆ 0.77697   ┆ 1000.0    ┆ 1000.0   │
│ f374beb07 ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆           ┆          │
│ 8157da12c ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ d4f…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0x72b05d0 ┆ 0         ┆ 177085716 ┆ 177085950 ┆ … ┆ -24.13787 ┆ -0.478259 ┆ 1000.0    ┆ 1000.0   │
│ 6e0a8ccc2 ┆           ┆ 9         ┆ 0         ┆   ┆ 1         ┆           ┆           ┆          │
│ a986bcda9 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a71…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0x808c50a ┆ 1         ┆ 177085716 ┆ 177085980 ┆ … ┆ -157.7935 ┆ -0.879849 ┆ 1000.0    ┆ 1000.0   │
│ 448b43810 ┆           ┆ 9         ┆ 0         ┆   ┆           ┆           ┆           ┆          │
│ 6958d188f ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8b3…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0xe7710c1 ┆ 0         ┆ 177085716 ┆ 177086010 ┆ … ┆ -21.74373 ┆ -0.206099 ┆ 1000.0    ┆ 1000.0   │
│ 82b8b3631 ┆           ┆ 0         ┆ 0         ┆   ┆ 3         ┆           ┆           ┆          │
│ 2fb7d90bc ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2fc…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘